miningWatchDog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Auth::routes(['verify' => true]);

Route::group(['prefix' => 'admin', 'middleware' => 'auth:admin', 'namespace' => 'Admin', 'as' => 'admin.'], function (){

    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('companies', 'CompanyController');
    Route::resource('users',  'UserController');


});

Auth::routes();

miningWatchDog/app/User.php
<?php

namespace App;

use App\Models\Membership;
use App\Models\Level;
use App\Models\Task;
use App\Models\Test;
use App\Models\Training;
use App\Models\Transaction;
use App\Models\Withdraw;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'active', 'contact', 'gender', 'balance'
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    function levels(){
        return $this->belongsToMany(Level::class, 'user_levels')->latest();
    }

    function currentLevels(){
    return $this->hasOne(Level::class, 'user_levels');
    }

    function trainings(){
        return $this->belongsToMany(Training::class);
    }

    function memberships(){
        return $this->belongsToMany(Membership::class);
    }

    function tests(){
        return $this->belongsToMany(Test::class, 'user_tests')->withPivot('id', 'status', 'body', 'video', 'deadline');
    }

    function videoTest(){
        return $this->belongsToMany(Test::class, 'user_tests')->withPivot('id', 'status', 'body', 'video', 'deadline')->whereTypeId(2);
    }
    function lastVideoTest(){
        return $this->belongsToMany(Test::class, 'user_tests')->withPivot('id', 'status', 'body', 'video', 'deadline')->whereTypeId(2)->orderBy('created_at', 'desc')->limit(1);
    }

    function writingTest(){
        return $this->belongsToMany(Test::class, 'user_tests')->withPivot('id', 'status', 'body', 'video', 'deadline')->whereTypeId(1);
    }
    function lastWritingTest(){
        return $this->belongsToMany(Test::class, 'user_tests')->withPivot('id', 'status', 'body', 'video', 'deadline')->whereTypeId(1)->orderBy('created_at', 'desc')->limit(1);
    }

    function currentVideoTest(){
        return $this->belongsToMany(Test::class, 'user_tests')->withPivot('id', 'status', 'body', 'video', 'deadline')->whereTypeId(2)->where('status' , '!=', 'failed')->where('status' , '!=', 'passed');
    }

    function currentWritingTest(){
        return $this->belongsToMany(Test::class, 'user_tests')->withPivot('id', 'status', 'body', 'video', 'deadline')->whereTypeId(1)->where('status' , '!=', 'failed')->where('status' , '!=', 'passed');
    }

    function tasks(){
        return $this->hasMany(Task::class);
    }

    function transactions(){
        return $this->hasMany(Transaction::class);
    }
    public function withdraws(){
        return $this->hasMany(Withdraw::class);
    }

    public function getCreatedAtAttribute($date)
    {
        return date('d-M-Y', strtotime($date));
    }

    public function getUpdatedAtAttribute($date)
    {
        return date('d-M-Y', strtotime($date));
    }
}

miningWatchDog/app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Task;
use App\Models\Transaction;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['users'] = User::orderBy('name', 'asc')->paginate(10);
        return view('admin.users.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("admin.users.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'           => 'required',
            'email'          => 'required',
            'password'       => 'required',
        ]);

        $data = [
            'name'         => $request->name,
            'email'        => $request->email,
            'password'     => bcrypt($request->password),
            'gender'       => $request->gender,
            'contact'      => $request->contact,
            'active'       => $request->active,
        ];

        $response = User::create($data);

        if ($response){
            return redirect()->route('admin.users.index')->with("success", "Completed Successfully.");
        }else{
            return redirect()->back()->withInput($request->all())->with("error", "Something went wrong. Please try again.");
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['transactions'] = Transaction::where('user_id', $id)->paginate(10);
        $data['tasks']        = Task::where('user_id', $id)->paginate(10);
        $tasks                = Task::where('user_id', $id)->where('status', 'approved')->get();
        $data['user']         = User::find($id);
        $totalEarned          = 0;

        foreach ($tasks as $task){
            $totalEarned = $totalEarned + $task->project->price;
        }
        $data['totalEarned'] = $totalEarned;

        return view("admin.users.show", $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['users'] = User::find($id);
        return view('admin.users.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'           => 'required',
            'email'          => 'required',
        ]);

        $data = [
            'name'         => $request->name,
            'email'        => $request->email,
            'gender'       => $request->gender,
            'contact'      => $request->contact,
            'active'       => $request->active,
        ];
        if ($request->password){
            $data['password']  = bcrypt($request->password);
            }

        $response = User::find($id)->update($data);

        if ($response){
            return redirect()->route('admin.users.index')->with("success", "Completed Successfully.");
        }else{
            return redirect()->back()->withInput($request->all())->with("error", "Something went wrong. Please try again.");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user           = User::find($id);
        $user->active     = $user->active == 0 ? 1 : 0;
        $response       = $user->save();

        if ($response){
            return redirect()->route('admin.users.index')->with("success", "Completed Successfully.");
        }else{
            return redirect()->back()->with("error", "Something went wrong. Please try again.");
        }
    }

    public function addToSpecial(Request $request, $id)
    {
        $user           = User::find($id);

        if ($request->action == 'special'){
            $user->special  = 1;
            $response       = $user->save();
        }
        elseif ($request->action == 'non-special'){
            $user->special  = 0;
            $response       = $user->save();
        }


        if ($response){
            return redirect()->back()->with("success", "Completed Successfully.");
        }else{
            return redirect()->back()->with("error", "Something went wrong. Please try again.");
        }
    }
}

miningWatchDog/resources/views/admin/users/create.blade.php
@extends('admin.layouts.master')

@section('content')

    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>Users</span>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>Create</span>
            </li>
        </ul>
        <div class="page-toolbar">
            <div class="btn-group pull-right open">
                <a href="{{ url()->previous() }}" class="btn red btn-sm" > <b><i class="fa fa-backward"></i> Back</b></a>
            </div>
        </div>

    </div>
    <h3 class="page-title">Users
        <small>Create User</small>
    </h3>

    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN VALIDATION STATES-->
            <div class="portlet light portlet-fit portlet-form bordered">

                <div class="portlet-body">
                    <!-- BEGIN FORM-->
                    <form action="{{ route('admin.users.store') }}" method="post">
                        @csrf
                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">

                                    <div class="form-group form-md-line-input">
                                        <input type="text" name="name" class="form-control" id="form_control_1" placeholder="Enter User Name" value="{{old('name')}}">
                                        <label>User Name</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <select class="form-control" name="gender">
                                            <option value="">Select Gender of User</option>
                                            <option value="Male" {{old('gender')=='Male'?'selected':''}}>Male</option>
                                            <option value="Female" {{old('gender')=='Female'?'selected':''}}>Female</option>
                                        </select>
                                        <label>Gender</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <input type="email" name="email" class="form-control" id="form_control_1" placeholder="Enter Email-Adress" value="{{old('email')}}">
                                        <label>Email-Address</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <input type="password" name="password" class="form-control" id="form_control_1" placeholder="Enter Password" value="{{old('password')}}">
                                        <label>password</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <input type="text" name="contact" class="form-control" id="form_control_1" placeholder="Enter Contact Number" value="{{old('contact')}}">
                                        <label>Contact No.</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <select class="form-control" name="active">
                                            <option value="">Status</option>
                                            <option value="1" selected>Active</option>
                                            <option value="0">Deactive</option>
                                        </select>
                                        <label>Status</label>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <input type="submit" class="btn green" value="Submit">
                                    <input type="reset" class="btn default" value="Reset">
                                </div>
                            </div>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
    </div>
@endsection

miningWatchDog/resources/views/admin/users/edit.blade.php
@extends('admin.layouts.master')

@section('content')

    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>Users</span>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>Edit</span>
            </li>
        </ul>
        <div class="page-toolbar">
            <div class="btn-group pull-right open">
                <a href="{{ url()->previous() }}" class="btn red btn-sm" > <b><i class="fa fa-backward"></i> Back</b></a>
            </div>
        </div>

    </div>
    <h3 class="page-title">Users
        <small>Edit User</small>
    </h3>

    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN VALIDATION STATES-->
            <div class="portlet light portlet-fit portlet-form bordered">

                <div class="portlet-body">
                    <!-- BEGIN FORM-->
                    <form action="{{ route('admin.users.update', $users->id) }}" method="post">
                        @csrf
                        {{ method_field('PATCH') }}
                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">

                                    <div class="form-group form-md-line-input">
                                        <input type="text" name="name" class="form-control" id="form_control_1" placeholder="Enter User Name" value="{{$users->name}}">
                                        <label>User Name</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <select class="form-control" name="gender">
                                            <option value="">Select Gender of User</option>
                                            <option value="Male" {{$users->gender == 'Male' ? 'selected':''}}>Male</option>
                                            <option value="Female" {{$users->gender == 'Female' ? 'selected':''}}>Female</option>
                                        </select>
                                        <label>Gender</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <input type="email" name="email" class="form-control" id="form_control_1" placeholder="Enter Email-Adress" value="{{$users->email}}">
                                        <label>Email-Address</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <input type="text" name="password" class="form-control" id="form_control_1" placeholder="Enter Password">
                                        <label>password</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <input type="text" name="contact" class="form-control" id="form_control_1" placeholder="Enter Contact Number" value="{{$users->contact}}">
                                        <label>Contact No.</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <select class="form-control" name="active">
                                            <option value="">Status</option>
                                            <option value="1" {{$users->active == '1' ? 'selected':''}}>Active</option>
                                            <option value="0" {{$users->active == '0' ? 'selected':''}}>Deactive</option>
                                        </select>
                                        <label>Status</label>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <input type="submit" class="btn green" value="Submit">
                                    <input type="reset" class="btn default" value="Reset">
                                </div>
                            </div>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
    </div>
@endsection

miningWatchDog/resources/views/admin/users/index.blade.php
@extends('admin.layouts.master')

@section('content')

    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>Users</span>
            </li>
        </ul>
        <div class="page-toolbar">
            <div class="btn-group pull-right open">
                <a href="{{ route('admin.users.create') }}" class="btn blue btn-sm" > <b><i class="fa fa-plus"></i> Add</b></a>
            </div>
        </div>

    </div>
    <h3 class="page-title">Users
    </h3>

    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN VALIDATION STATES-->
            <div class="portlet light portlet-fit bordered">

                <div class="portlet-body flip-scroll">
                    <table class="table table-bordered table-striped flip-content">
                        <thead class="flip-content">
                        <tr>
                            <th width="75px"> Sr No. </th>
                            <th> User Name </th>
                            <th> Gender </th>
                            <th> Email Address </th>
                            <th> Total Tasks </th>
                            <th> Status </th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @php
                        $i = 0;
                        @endphp
                            @forelse($users as $user)
                                <tr class="table-row-clickable" onclick="window.location = '{{route('admin.users.show', $user->id)}}'">

                                    <td> {{ ++$i }} </td>
                                    <td> {{ $user->name }} </td>
                                    <td> {{ $user->gender }} </td>
                                    <td> {{ $user->email }} </td>
                                    <td> {{ $user->name }} </td>
                                    <td> {{ $user->active == 0 ? 'Deactive':'Active' }} </td>
                                    <td>
                                        <form action="{{ route('admin.users.destroy',$user->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <a class="btn btn-primary" href="{{ route('admin.users.edit', $user->id) }}">Edit</a>
                                            @if($user->active == 0)
                                                <button type="submit" class="btn btn-success btn-outline sbold uppercase">Active</button>
                                            @else
                                                <button type="submit" class="btn btn-danger btn-outline sbold uppercase">Inactive</button>
                                            @endif

                                        </form>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="7">
                                        Data Not Found
                                    </td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                    <div class="text-center">
                    {{$users->links()}}
                    </div>
            </div>
        </div>
    </div>
@endsection

miningWatchDog/resources/views/admin/users/show.blade.php
@extends('admin.layouts.master')

@section('content')
    <style>
        .description{
            background: #8080800d;
            padding: 1px 10px 15px 25px;
        }
    </style>


    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span> User </span>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span> Show </span>
            </li>
        </ul>
        <div class="page-toolbar">
            <div class="btn-group pull-right open">
                <a href="{{ url()->previous() }}" class="btn red btn-sm" > <b>Back</b>
                    <i class="fa fa-backward"></i>
                </a>
            </div>
        </div>

    </div>


    <div class="row">
        <div class="col-sm-6">
            <h3 class="d-inline-block page-title"><b>{{ $user->name }}</b></h3>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="portlet light portlet-fit bordered">

                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover">
                        <tr>
                            <th>User Name</th>
                            <td>{{$user->name}}</td>
                        </tr>

                        <tr>
                            <th>Gender</th>
                            <td>{{$user->gender}}</td>
                        </tr>

                        <tr>
                            <th>Email Address</th>
                            <td>{{$user->email}}</td>
                        </tr>

                        <tr>
                            <th>Contact No.</th>
                            <td>{{$user->contact}}</td>
                        </tr>

                        <tr>
                            <th>Status</th>
                            <td>{{$user->active}}</td>
                        </tr>

                        <tr>
                            <th>Total Earned</th>
                            <td>{{ $totalEarned }}</td>
                        </tr>

                        <tr>
                            <th>Balance</th>
                            <td>{{ $user->balance }}</td>
                        </tr>

                        <tr>
                            <th>Writing Points</th>
                            <td>{{ $user->writing_points }}</td>
                        </tr>

                        <tr>
                            <th>Video Points</th>
                            <td>{{ $user->video_points }}</td>
                        </tr>

                        <tr>
                            <th>Created</th>
                            <td>{{$user->created_at}}</td>
                        </tr>

                        <tr>
                            <th>Last Update</th>
                            <td>{{$user->updated_at}}</td>
                        </tr>

                    </table>

                </div>
            </div>
        </div>
    </div>
@endsection