miningWatchDog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Auth::routes(['verify' => true]);

Route::group(['prefix' => 'admin', 'middleware' => 'auth:admin', 'namespace' => 'Admin', 'as' => 'admin.'], function (){

    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('companies', 'CompanyController');
    Route::resource('users',  'UserController');


});

Auth::routes();

miningWatchDog/app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{

    protected $fillable = ['name', 'website', 'country', 'logo', 'star_rating', 'description', 'company_status', 'note', 'review_question', 'legitimacy'];
//    protected $dates = ['deadline'];

    public function getCreatedAtAttribute($date)
    {
        return date('d-M-Y', strtotime($date));
    }

    public function getUpdatedAtAttribute($date)
    {
        return date('d-M-Y', strtotime($date));
    }
}

miningWatchDog/app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Company;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['companies'] = Company::orderBy('created_at', 'desc')->paginate(10);
        return view('admin.companies.index', $data);
    }

    public function create()
    {
        return view("admin.companies.create");
    }

    public function store(Request $request)
    {
        $request->validate([
            'name'              => 'required',
            'description'       => 'required',
            'country'           => 'required',
            'website'           => 'required',
            'logo'              => 'required',
            'star_rating'       => 'required',
            'company_status'    => 'required',
            'note'              => 'required',
            'review_question'   => 'required',
            'legitimacy'        => 'required',

        ]);

        $company                    = new Company();
        $company->name              = $request->name;
        $company->description       = $request->description;
        $company->full_description  = $request->full_description;
        $company->country           = $request->country;
        $company->website           = $request->website;
        $company->star_rating       = $request->star_rating;
        $company->company_status    = $request->company_status;
        $company->note              = $request->note;
        $company->review_question   = $request->review_question;
        $company->legitimacy        = $request->legitimacy;

        if ($request->hasFile("logo") && $request->file('logo')->isValid()) {
            $filename           = $request->file('logo')->getClientOriginalName();
            $filename           = time()."-".$filename;
            $destinationPath    = public_path('/images');
            $company->logo      = "images/".$filename;
            $request->file('logo')->move($destinationPath, $filename);
        }

        $response = $company->save();

        if ($response) {
            return redirect()->route('admin.companies.index')->with("success", "Completed Successfully.");
        } else {
            return redirect()->back()->withInput($request->all())->with("error", "Something went wrong. Please try again.");
        }
    }

    public function show(Company $company)
    {
        $data['company'] = $company;
        return view('admin.companies.show', $data);
    }

    public function edit(Company $company)
    {
        $data['company'] = $company;
        return view('admin.companies.edit', $data);
    }


    public function update(Request $request, Company $company)
    {
        $request->validate([
            'name'          => 'required',
            'description'   => 'required',
            'country'       => 'required',
            'website'       => 'required',
            'logo'          => 'required',
            'star_rating'   => 'required',
            'company_status' => 'required',
            'note'          => 'required',
            'review_question' => 'required',
            'legitimacy'    => 'required',

        ]);

        $company->name          = $request->name;
        $company->description   = $request->name;
        $company->country       = $request->name;
        $company->website       = $request->name;
        $company->logo          = $request->name;
        $company->star_rating   = $request->name;
        $company->company_status= $request->company_status;
        $company->note          = $request->note;
        $company->review_question = $request->review_question;
        $company->legitimacy    = $request->legitimacy;

        $response = $company->save();

        if ($response) {
            return redirect()->route('admin.companies.index')->with("success", "Completed Successfully.");
        } else {
            return redirect()->back()->withInput($request->all())->with("error", "Something went wrong. Please try again.");
        }
    }


    public function destroy(Company $company)
    {
        $company->active = $company->active == 0 ? 1 : 0;
        $response = $company->save();

        if ($response) {
            return redirect()->back()->with("success", "Completed Successfully.");
        } else {
            return redirect()->back()->with("error", "Something went wrong. Please try again.");
        }
    }
}

miningWatchDog/resources/views/admin/companies/create.blade.php
@extends('admin.layouts.master')

@section('content')

    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>Projects</span>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>Create</span>
            </li>
        </ul>
        <div class="page-toolbar">
            <div class="btn-group pull-right open">
                <a href="{{ url()->previous() }}" class="btn red btn-sm" > <b><i class="fa fa-backward"></i> Back</b></a>
            </div>
        </div>

    </div>
    <h3 class="page-title">Projects
        <small>Create Project</small>
    </h3>

    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN VALIDATION STATES-->
            <div class="portlet light portlet-fit portlet-form bordered">

                <div class="portlet-body">
                    <!-- BEGIN FORM-->
                    <form action="{{ route('admin.companies.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">

                                    <div class="form-group form-md-line-input">
                                        <input type="text" name="name" class="form-control" id="form_control_1" placeholder="Enter company name" value="{{old('name')}}">
                                        <label>Company Name</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <input type="text" name="website" class="form-control" id="form_control_1" placeholder="Enter website name" value="{{old('Website')}}">
                                        <label>Website Name</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <input type="text" name="country" class="form-control" id="form_control_1" placeholder="Enter country name" value="{{old('country')}}">
                                        <label>Country Name</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <input type="file" name="logo" class="form-control" id="form_control_1" value="{{old('logo')}}">
                                        <label>Add Logo</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <input type="text" name="description" class="form-control" id="form_control_1" placeholder="Enter full description" value="{{old('full_description')}}">
                                        <label>Description</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <input type="number" name="star_rating" class="form-control" id="form_control_1" placeholder="Enter star rating" value="{{old('star_rating')}}">
                                        <label>Star Rating</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <input type="text" name="review_question" class="form-control" id="form_control_1" placeholder="Enter Review Question" value="{{old('review_question')}}">
                                        <label>Review Question</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <input type="text" name="note" class="form-control" id="form_control_1" placeholder="Enter note" value="{{old('note')}}">
                                        <label>Note</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <select class="form-control" name="company_status">
                                            <option value="">Company Status</option>
                                            <option value="approve" selected>Legitimate Company and Mining WatchDog Approved.</option>
                                            <option value="scam">Scam Company and Not Approved By Mining WatchDog.</option>
                                            <option value="not_sure">Not sure, probably best to stay clear of this company.</option>
                                        </select>
                                        <label>Company Status</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <select class="form-control" name="legitimacy">
                                            <option value="">Legitimacy</option>
                                            <option value="green" selected>Legitimate Company and Mining WatchDog Approved.</option>
                                            <option value="yellow">Scam Company and Not Approved By Mining WatchDog</option>
                                            <option value="red">Not sure, probably best to stay clear of this company.</option>
                                        </select>
                                        <label>Legitimacy</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <select class="form-control" name="active">
                                            <option value="">Status</option>
                                            <option value="1" selected>Active</option>
                                            <option value="0">Inactive</option>
                                        </select>
                                        <label>Status</label>
                                    </div>

                                    <div class="form-group form-md-line-input">
                                        <textarea name="full_description" class="summernote" placeholder="Description"></textarea>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <input type="submit" class="btn green" value="Submit">
                                    <input type="reset" class="btn default" value="Reset">
                                </div>
                            </div>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
    </div>
@endsection

miningWatchDog/resources/views/admin/companies/edit.blade.php
@extends('admin.layouts.master')

@section('content')

    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>Projects</span>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>Edit</span>
            </li>
        </ul>
        <div class="page-toolbar">
            <div class="btn-group pull-right open">
                <a href="{{ url()->previous() }}" class="btn red btn-sm" > <b><i class="fa fa-backward"></i> Back</b></a>
            </div>
        </div>

    </div>
    <h3 class="page-title">Projects
        <small>Edit Project</small>
    </h3>

    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN VALIDATION STATES-->
            <div class="portlet light portlet-fit portlet-form bordered">

                <div class="portlet-body">
                    <!-- BEGIN FORM-->
                    <form action="{{ route('admin.projects.update', $project->id) }}" method="post">
                        @csrf
                        {{ method_field('PATCH') }}

                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">

                                    <div class="form-group form-md-line-input">
                                        <input type="text" name="name" value="{{ $project->name }}" class="form-control" id="form_control_1" placeholder="Enter Project Name">
                                        <label for="form_control_1">Project Name</label>
                                    </div>

                                    <div class="row margin-bottom-25">
                                        <div class="col-sm-6">
                                            <div class="form-group form-md-line-input">
                                                <input type="number" name="quantity" value="{{ $project->quantity }}" class="form-control" id="mask_number form_control_1" placeholder="Enter Number of Tasks">
                                                <label for="form_control_1">Number of Tasks</label>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group form-md-line-input">
                                                <input type="number" name="deadline" value="{{ $project->deadline }}" class="form-control datetime" id="form_control_1" placeholder="Time Awarded for task in hours">
                                                <label for="form_control_1">Task Deadline <small>(in hours)</small></label>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row margin-bottom-25">
                                        <div class="col-sm-6">
                                            <div class="form-group form-md-line-input">
                                                <input type="number" name="price" value="{{ $project->price }}" class="form-control" id="form_control_1" placeholder="Enter Price for a Task">
                                                <label>Price</label>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group form-md-line-input">
                                                <input type="number" name="points" value="{{ $project->points }}" class="form-control" id="form_control_1" placeholder="Enter Points for a Task" value="{{old('points')}}">
                                                <label>Points</label>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row margin-bottom-25">
                                        <div class="col-sm-6">
                                            <div class="form-group form-md-line-input">
                                                <select class="form-control" id="form_control_1" name="level">
                                                    <option value="">Select User Level</option>
                                                    @foreach($levels as $level)
                                                        <option value="{{ $level->id }}" {{ $project->level_id == $level->id ? 'selected' : ''}}>{{ $level->name }}</option>
                                                    @endforeach
                                                </select>
                                                <label for="form_control_1">Project Level</label>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group form-md-line-input">
                                                <select class="form-control" id="form_control_1" name="active">
                                                    <option value="">Status</option>
                                                    <option value="1" {{ $project->active = 1 ? 'selected' : ''}}>Active</option>
                                                    <option value="0" {{ $project->active = 0 ? 'selected' : ''}}>Inactive</option>
                                                </select>
                                                <label for="form_control_1">Project Status</label>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="portlet-body form">
                                        <div class="form-body">
                                            <div class="form-group last">
                                                <textarea name="description" class="summernote" cols="30" rows="10">{!! $project->description !!}</textarea>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <input type="submit" class="btn green" value="Submit">
                                    <input type="reset" class="btn default" value="Reset">
                                </div>
                            </div>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
    </div>
@endsection

miningWatchDog/resources/views/admin/companies/index.blade.php
@extends('admin.layouts.master')

@section('content')

    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>Company</span>
            </li>
        </ul>
        <div class="page-toolbar">
            <div class="btn-group pull-right open">
                <a href="{{ route('admin.companies.create') }}" class="btn blue btn-sm" > <b><i class="fa fa-plus"></i> Add</b></a>
            </div>
        </div>

    </div>
    <h3 class="page-title">Company
    </h3>

    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN VALIDATION STATES-->
            <div class="portlet light portlet-fit bordered">

                <div class="portlet-body flip-scroll">
                    <table class="table table-bordered table-striped flip-content">
                        <thead class="flip-content">
                        <tr>
                            <th width="75px"> Sr No. </th>
                            <th> Company Name </th>
                            <th> Country </th>
                            <th> Website </th>
                            <th> Rating </th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @php
                            $i = 0;
                        @endphp
                        @forelse($companies as $company)
                            <tr class="table-row-clickable" onclick="window.location = '{{ route('admin.companies.show', $company->id) }}'">
                                <td> {{ ++$i }} </td>
                                <td> {{ $company->name }} </td>
                                <td> {{ $company->country }} </td>
                                <td> {{ $company->website }} </td>
                                <td> {{ $company->star_rating }} </td>
                                <td> {{ $company->active == 1 ? 'Active' : 'Inactive'}} </td>
                                <td>
                                    <form action="{{ route('admin.companies.destroy',$company->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <a class="btn btn-primary btn-sm" href="{{ route('admin.companies.edit', $company->id) }}">Edit</a>
                                        @if($company->active == 0)
                                            <button type="submit" class="btn btn-success btn-outline btn-sm sbold uppercase">Active</button>
                                        @else
                                            <button type="submit" class="btn btn-danger btn-outline btn-sm sbold uppercase">Inactive</button>
                                        @endif
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="9">
                                    Data Not Found
                                </td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                    <div class="text-center">
                        {{$companies->links()}}
                    </div>
                </div>
            </div>
        </div>
@endsection

miningWatchDog/resources/views/admin/companies/show.blade.php
@extends('admin.layouts.master')

@section('content')
    <style>
        .description{
            background: #8080800d;
            padding: 1px 10px 15px 25px;
        }
    </style>


    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span> Company</span>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span> Show</span>
            </li>
        </ul>
        <div class="page-toolbar">
            <div class="btn-group pull-right open">
                <a href="{{ url()->previous() }}" class="btn red btn-sm" > <b>Back</b>
                    <i class="fa fa-backward"></i>
                </a>
            </div>
        </div>

    </div>

    <h3 class="page-title">Details of <b>{{ $project->name }}</b>
    </h3>

    <div class="row">
        <div class="col-md-12">
            <div class="portlet light portlet-fit bordered">

                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover">
                        <tr>
                            <th>Project Name</th>
                            <td>{{$project->name}}</td>
                        </tr>

                        <tr>
                            <th>Number of Tasks</th>
                            <td>{{$project->quantity}}</td>
                        </tr>
                        <tr>
                            <th>Available Tasks</th>
                            <td>{{$project->available   }}</td>
                        </tr>

                        <tr>
                            <th>User Level for Project</th>
                            <td>{{$project->level->name}}</td>
                        </tr>

                        <tr>
                            <th>Deadline</th>
                            <td>{{$project->deadline ?? 'None'}}</td>
                        </tr>

                        <tr>
                            <th>Price for a Task</th>
                            <td>{{$project->price}}</td>
                        </tr>

                        <tr>
                            <th>Points for a Task</th>
                            <td>{{$project->points}}</td>
                        </tr>

                        <tr>
                            <th>Created</th>
                            <td>{{$project->created_at}}</td>
                        </tr>

                        <tr>
                            <th>Last Update</th>
                            <td>{{$project->updated_at}}</td>
                        </tr>

                    </table>

                    <h3 >Description</h3>
                    <div class="description">{!! $project->description !!}</div>

                </div>
            </div>
        </div>
    </div>
@endsection